# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.236
loader_version_range=[1,)

## Mod Properties

mod_id=beloong
mod_name=BeLoong Core
mod_license=MIT
mod_version=0.8.3
mod_logo_file=logo.png
mod_authors=PorkChop-ZLG
mod_description=The core mod for modpack BeLoong.

mod_group_id=com.zonlong.beloong
